/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { GoLocation, GoMail } from "react-icons/go";
import { BsTelephone } from "react-icons/bs";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import gbemi from "../public/gbemi.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import { useForm } from "react-hook-form";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const { register, handleSubmit } = useForm();

  const onSubmit = (formData) => {
    window.location.href = `mailto:kukoyioluwagbemisola@gmail.com?subject=${formData.subject}&body=Hi, My Name is ${formData.name}. ${formData.message} (${formData.email})`;
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Data Scientist</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Kukoyi Oluwagbemisola
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Elevating Insights Through Data.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              A passionate data scientist with a flair for extracting actionable
              insights from complex datasets. Proficient in various analytical
              tools and machine learning techniques. Committed to driving
              data-driven solutions for real-world challenges.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/i/flow/login?redirect_after_login=%2FGbemy_data"  className="cursor-pointer"  rel="noreferrer"><AiFillTwitterCircle /></a>

              <a href="AQFs0o9jwOb3zAAAAYn5bk3YhTdV9WQJ5cHoA0t7FM8LeX2oYV428WI_kmtFijxXdrbFfAddu" target="_blank"  className="cursor-pointer" rel="noreferrer"><AiFillLinkedin /></a>
              
              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={gbemi} layout="fill" objectFit="cover" alt="" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My Story</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Zainab Kukoyi is a talented and passionate data scientist hailing
              from Lagos State, Nigeria. With a keen eye for detail and a strong
              background in statistics and data analysis, she has become a
              result-oriented expert in the field. Zainab's journey in the world
              of data science has been marked by her proficiency in various
              analytical tools and programming languages. She is adept at using
              visualization tools like PowerBi to derive valuable insights and
              create impactful visualizations from complex datasets. <br/>
              Additionally, her skillset includes expertise in Python (Numpy,
              Seaborn, Pandas, Matplotlib), R, SQL, and Microsoft Excel, making
              her a versatile and sought-after data analyst. Her experiences
              have shaped her into an analytical thinker and a methodical
              problem solver. Zainab's organizational and communication skills
              have allowed her to approach complex data challenges with ease and
              deliver effective solutions.  <br/> Her passion lies in harnessing the
              power of data to solve real-world problems and drive data-driven
              decision-making. Throughout her career, Zainab has demonstrated
              her capabilities as a data analyst at GlobalShala, where she
              played a key role in evaluating marketing data and producing data
              visualizations that helped optimize campaigns and cut costs
              significantly. She has also contributed to the Futa-Laboratory for
              interdisciplinary Statistical analysis (FUTA-LISA), where she
              collaborated on diverse projects, expanding her knowledge and
              expertise in data analysis using R.  <br/>  <br/> Zainab's commitment to data
              excellence extends to her academic achievements as well. She
              completed her Bachelor's degree in Statistics from the Federal
              University of Technology Akure, and further honed her skills with
              a Nanodegree in Data Analysis from Udacity. In her quest to
              continuously grow and learn, Zainab took part in a Data Analysis &
              Business Intelligence program at Octave Incorporations, where she
              utilized PowerBi to clean, model, and present data insights
              through interactive dashboards. Zainab Kukoyi's exceptional
              dedication to data science and her drive to make an impact set her
              apart. As she envisions a future of combining her passion for data
              with real-world challenges, she is poised to make meaningful
              contributions to the world of data science and beyond.
            </p>
          </div>
          <div className=" py-10">
            <h3 className="text-3xl py-1 dark:text-white ">ELEVATOR PITCH</h3>
            <a href="https://drive.google.com/file/d/12cyJpSiSHpbqXrIzf4XG8zZACvJ7YtOe/view?usp=drivesdk">
              <button className="mx-auto rounded-lg border p-3 text-gray-800 dark:text-gray-200">
                click to watch video
              </button>
            </a>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <a
              href="https://www.datascienceportfol.io/zainabkukoyi"
              target="_blank"
              rel="noreferrer"
            >
              <button className="mx-auto rounded-lg border p-3 text-gray-800 dark:text-gray-200">
                click to redirect to portfolio page
              </button>
            </a>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 text-gray-800 dark:text-gray-200 text-center ">
              Contact Me
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 text-center">
              Ready to unlock the potential of your data or explore new
              opportunities in the world of data science? Don't hesitate to get
              in touch! Whether you're seeking insights, collaboration, or
              simply a conversation about data-driven solutions, I'm here to
              connect. Reach out via the provided contacts, and let's start a
              meaningful dialogue that could lead to innovative discoveries and
              exciting possibilities.
            </p>

            <ul className="contact text-gray-800 dark:text-gray-200">
              <li className="py-2 flex gap-1 items-center">
                <BsTelephone />
                <p>+2349034330716</p>
              </li>
              <li className="py-2 flex gap-1 items-center">
                <GoLocation /> <p>Lagos, Nigeria.</p>
              </li>
              <li className="py-2 flex gap-1 items-center">
                <GoMail />
                <p>kukoyioluwagbemisola@gmail.com</p>
              </li>
            </ul>
          </div>

          <div className="mt-[36px]">
            <h2 className="text-[28px] text-gray-600 font-bold mb-4 text-center">
              Send A Mail
            </h2>
            <form
              onSubmit={handleSubmit(onSubmit)}
              action=""
              className="flex flex-col space-y-4 md:px-[10%]  "
            >
              <div className="flex gap-2   flex-col md:flex-row md:space-x-2 md:justify-between">
                <input
                  {...register("name")}
                  placeholder="Name"
                  type="text"
                  className="contactInput w-full"
                />
                <input
                  {...register("email")}
                  placeholder="Email"
                  type="email"
                  className="contactInput w-full"
                />
              </div>
              <input
                {...register("subject")}
                placeholder="Subject"
                type="text"
                className="contactInput"
              />
              <textarea
                {...register("message")}
                placeholder="Message"
                className="contactInput"
              ></textarea>
              <button
                type="submit"
                className="bg-teal-600  dark:bg-teal-400 md:w-[70%] w-full   self-center py-5 px-[16px] md:px-4 rounded-md text-gray-800 dark:text-gray-200 font-bold text-lg"
              >
                Submit
              </button>
            </form>
          </div>
          <p className="text-center text-gray-800 dark:text-gray-200 text-sm mt-[36px] ">
            Copyright © {new Date().getFullYear()} Kukoyi Oluwagbemisola
          </p>
        </section>
      </main>
    </div>
  );
}
