/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { GoLocation, GoMail } from "react-icons/go";
import { BsTelephone } from "react-icons/bs";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import gbemi from "../public/gbemi.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import { useForm } from "react-hook-form";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const { register, handleSubmit } = useForm();

  const onSubmit = (formData) => {
    window.location.href = `mailto:kukoyioluwagbemisola@gmail.com?subject=${formData.subject}&body=Hi, My Name is ${formData.name}. ${formData.message} (${formData.email})`;
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Oluwagbemisola Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-6 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 lg:mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Data Scientist</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center lg:p-10 py-10">
            <h2 className="text-3xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Kukoyi Oluwagbemisola
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Elevating Insights Through Data.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              A passionate data scientist with a flair for extracting actionable
              insights from complex datasets. Proficient in various analytical
              tools and machine learning techniques. Committed to driving
              data-driven solutions for real-world challenges.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a
                href="https://twitter.com/i/flow/login?redirect_after_login=%2FGbemy_data"
                className="cursor-pointer"
                rel="noreferrer"
              >
                <AiFillTwitterCircle />
              </a>

              <a
                href="AQFs0o9jwOb3zAAAAYn5bk3YhTdV9WQJ5cHoA0t7FM8LeX2oYV428WI_kmtFijxXdrbFfAddu"
                target="_blank"
                className="cursor-pointer"
                rel="noreferrer"
              >
                <AiFillLinkedin />
              </a>

              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 relative overflow-hidden mt-10 lg:mt-20 md:h-96 md:w-96">
              <Image src={gbemi} layout="fill" objectFit="cover" alt="" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">My Story</h3>
            <p className="text-md py-2 leading-8  text-gray-800 dark:text-gray-200">
              Experienced Freelance Data Analyst with about 2 years of proven
              expertise in managing data collection and preprocessing tasks for
              a diverse client base spanning multiple countries. Adept at
              developing questionnaires, ensuring data quality, and employing
              the most effective analytical approaches. Notably contributed to
              cost- cutting initiatives during a brief tenure at GlobalShala,
              showcasing proficiency in data evaluation and visualization.<br/> As a
              Student Intern at the Lagos Bureau of Statistics, actively
              participated in survey design, data compilation, and report
              generation, emphasizing strong communication of actionable
              insights through visualizations. Armed with a Nanodegree in Data
              Analysis from Udacity and a solid academic foundation with a
              Bachelor's degree in Statistics.<br/>  I am currently enrolled in the Data
              Science program at ExploreAI Academy, demonstrating proficiency in
              SQL, Power BI, and Python for comprehensive data manipulation and
              analysis. Seeking opportunities to apply my skills and contribute
              to data-driven decision-making processes.
            </p>
          </div>
          {/* <div className=" py-10">
            <h3 className="text-3xl py-1 dark:text-white ">ELEVATOR PITCH</h3>
            <a href="https://drive.google.com/file/d/12cyJpSiSHpbqXrIzf4XG8zZACvJ7YtOe/view?usp=drivesdk">
              <button className="mx-auto bg-gray-900 rounded-lg border p-3 text-gray-200">
                click to watch video
              </button>
            </a>
          </div> */}
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <a
              href="https://www.datascienceportfol.io/zainabkukoyi"
              target="_blank"
              rel="noreferrer"
            >
              <button className="mx-auto bg-gray-900 rounded-lg border p-3 text-gray-200">
                click to redirect to my  portfolio page
              </button>
            </a>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 text-gray-800 dark:text-gray-200 text-center ">
              Lets Talk!
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200 text-center mb-5">
              Ready to unlock the potential of your data or explore new
              opportunities in the world of data science? Don't hesitate to get
              in touch! Whether you're seeking insights, collaboration, or
              simply a conversation about data-driven solutions, I'm here to
              connect. Reach out via the provided contacts, and let's start a
              meaningful dialogue that could lead to innovative discoveries and
              exciting possibilities.
            </p>

            <ul className="contact text-gray-800 dark:text-gray-200">
              <li className="py-2 flex gap-1 items-center">
                <BsTelephone />
                <p>+2349034330716</p>
              </li>
              <li className="py-2 flex gap-1 items-center">
                <GoLocation /> <p>Lagos, Nigeria.</p>
              </li>
              <li className="py-2 flex gap-1 items-center">
                <GoMail />
                <p>kukoyioluwagbemisola@gmail.com</p>
              </li>
            </ul>
          </div>

          <div className="mt-[36px]">
            <h2 className="text-[28px] text-gray-600 font-bold mb-4 text-center">
              Send A Mail
            </h2>
            <form
              onSubmit={handleSubmit(onSubmit)}
              action=""
              className="flex flex-col space-y-4 md:px-[10%]  "
            >
              <div className="flex gap-2   flex-col md:flex-row md:space-x-2 md:justify-between">
                <input
                  {...register("name")}
                  placeholder="Name"
                  type="text"
                  className="contactInput w-full"
                />
                <input
                  {...register("email")}
                  placeholder="Email"
                  type="email"
                  className="contactInput w-full"
                />
              </div>
              <input
                {...register("subject")}
                placeholder="Subject"
                type="text"
                className="contactInput"
              />
              <textarea
                {...register("message")}
                placeholder="Message"
                className="contactInput"
              ></textarea>
              <button
                type="submit"
                className="bg-teal-600  dark:bg-teal-400 md:w-[70%] w-full   self-center py-5 px-[16px] md:px-4 rounded-md text-gray-800 dark:text-gray-200 font-bold text-lg"
              >
                Submit
              </button>
            </form>
          </div>
          <p className="text-center text-gray-800 dark:text-gray-200 text-sm mt-[36px] ">
            Copyright © {new Date().getFullYear()} Kukoyi Oluwagbemisola
          </p>
        </section>
      </main>
    </div>
  );
}
